### PR TITLE
Create-category-api

### PR DESCRIPTION
**Pull request by DeanHoang**
I created api for category, but I still have a problem with the account's role.
I dont know why it can not take the role of the account.
So, I will fix it soon.
Please review the other and give me feedback

### CODE REVIEW

**Comment by vancuong196** [comment]
Please add .gitignore, this pull request has 63 files changed, most of them should be ignored.

**Comment by vancuong196** [comment]
Where is your git ignore file?

**Comment by DeanHoang** [comment]
> Please add .gitignore, this pull request has 63 files changed, most of them should be ignored.

**Comment by DeanHoang** [comment]
> Where is your git ignore file?

Jessie had added ignore files but when I add, it doesn't work

**Comment by DeanHoang** [comment]
> Where is your git ignore file?
> Take a look https://gist.github.com/vmandic/ac2ecc9c24f6899ee0ec46e4ce444a0e

image
I think it is mine. But it can not ignore the file I need.

**Comment by vancuong196** [comment]
> > Where is your git ignore file?
> > Take a look https://gist.github.com/vmandic/ac2ecc9c24f6899ee0ec46e4ce444a0e
> 
> image
> I think it is mine. But it can not ignore the file I need.

Move it to your project folders. Or change the ignore rule on this file

**Comment by DeanHoang** [comment]
> > > Where is your git ignore file?
> > > Take a look https://gist.github.com/vmandic/ac2ecc9c24f6899ee0ec46e4ce444a0e
> > 
> > 
> > image
> > I think it is mine. But it can not ignore the file I need.
> 
> Move it to your project folders. Or change the ignore rule on this file

I created and added a new one in the BE. Do I need to delete the old one?

**Comment by DeanHoang** [comment]
I'm sorry but may I add another pull request for this, @vancuong196 ?

**Comment by vancuong196** [comment]
Yes, you can. Add gitignore will remove many files in this repo.

**Comment by DeanHoang** [comment]
> Yes, you can. Add gitignore will remove many files in this repo.

I created another pull request. So, I will close this request. Please review the new one.
Thank you.

**Pull request closed without merging**
